### PR TITLE
Add conda recipe, compilation fixes for Windows

### PR DESCRIPTION
**Pull request by ryanvolz**
This adds a conda recipe based on the `gr_modtool newmod` template recipe. To get it to build on Windows, this also includes a number of commits for MSVC/Windows compatibility. I've tested this by building the packages in CI: https://github.com/ryanvolz/gr-lora_sdr/actions/runs/4659711205. These will packages are now on my [anaconda.org channel](https://anaconda.org/ryanvolz/gnuradio-lora_sdr) and will be included in the next release of [radioconda](https://github.com/ryanvolz/radioconda).

If you're interested in setting up CI builds based on this recipe, that's a simple change that I can add to this PR.

### CODE REVIEW

**Comment by tapparelj** [comment]
Hello @ryanvolz,
Thanks for the work you did! 
I will check it and let you know if I have any questions or comments

**Comment by tapparelj** [comment]
Hello,
it is very cool to be able to use conda to install the OOT module and it works like a charm! 

I'm not familiar with how to maintain a conda package so there is a few things I'm wondering:
- The example flowgraphs don't seem to be included in the installation. This render the utilization quite tricky as there is no information on what you are supposed to do after installing the package. Is it possible to add a line in the anaconda package page to say that usage examples are available on the git?
- Also related to the ease of utilization, the package doesn't install gnuradio-grc, gnuradio-uhd or gnuradio-soapy, which are quite useful. Is it possible to have them as dependencies? 
- I'm not sure what a CI build really is. Does it allow to automatically build and update the conda package available in your conda channel or does it only tries to build the package at each new commit to verify that no dependencies broke? 
- Finally, completely optional and just for propaganda, would it be possible to have a line similar to "If you find this module useful for your project, please consider citing the publication https://arxiv.org/abs/2002.08208."

**Comment by ryanvolz** [comment]
>     * The example flowgraphs don't seem to be included in the installation. This render the utilization quite tricky as there is no information on what you are supposed to do after installing the package. Is it possible to add a line in the anaconda package page to say that usage examples are available on the git?

I think we could do better and add some CMake to install the examples to  `${GR_PKG_DATA_DIR}/examples/lora_sdr` in a similar manner to the in-tree modules: https://github.com/gnuradio/gnuradio/blob/main/gr-uhd/examples/grc/CMakeLists.txt

(This would actually be a good change to contribute to the gr-modtool OOT template, in my mind.)

If there's also some text you want to add to the description, that's fine too.

>     * Also related to the ease of utilization, the package doesn't install gnuradio-grc, gnuradio-uhd or gnuradio-soapy, which are quite useful. Is it possible to have them as dependencies?

It's possible, but at least for `gnuradio-uhd` I would be hesitant to force installing modules that are not strictly necessary. Instructing folks to install the `gnuradio` meta-package in addition to `gnuradio-lora_sdr` would catch all 3 of those in-tree modules and not restrict what the more experienced users could do.

That said, if it's your feeling that `gnuradio-lora_sdr` is practically useless without those modules, we can add them as run dependencies.

>     * I'm not sure what a CI build really is. Does it allow to automatically build and update the conda package available in your conda channel or does it only tries to build the package at each new commit to verify that no dependencies broke?

It could be both. Primarily it would do the latter, running the build against pull requests and commits to any branch to verify that the package builds and potentially running tests. Optionally, you could also set it up to upload packages to an anaconda.org channel (although not mine, since you need a private key) for any commits to a specified branch (usually master/main). More details are in the [README](.conda/README.md).

>     * Finally, completely optional and just for propaganda, would it be possible to have a line similar to "If you find this module useful for your project, please consider citing the publication https://arxiv.org/abs/2002.08208."

Yes, that can be added at the end of the description.

**Comment by ryanvolz** [comment]
Alright, the examples have been added to the package and the publication has been added to the description.

**Comment by tapparelj** [comment]
Hello,
thanks for the addition to made! 
Indeed, requiring UHD, soapy or GRC is not the best option and it is easy to get them all with the gnuradio package.
I will look more into how to make and manage a conda package as this seems very useful!

**Pull request merged**
