### PR TITLE
code modified to write hex to date_timestamped file

### PR DESCRIPTION
**Pull request by alphapats**
crc_verif block amended with follwoing additional capabilities:- 
write hex to file (filename : output_datetimestamp.txt) 
Added hex output port to pass hex as msg (message_sink)
 
Screenshot from 2024-01-29 19-31-45

### CODE REVIEW

**Comment by tapparelj** [comment]
Hi @alphapats,
thanks for the additions all seems to work! The message output of the hex values is nice option that could be useful.
For the hex to file I see the usefulness of saving timestamped payload however I have a few concerns with the current implementation:
- The inability to select the saving path and/or saving filename makes it difficult to use when not in a very specific execution or test case.
- Creating one file per received frame can be very bad if someone simulate Tx and Rx to get error rates for example, quickly generating thousands of files.
I would gladly merge the part which adds the _Hex_ output, but for the other, the following would be more practical:
- make a new block that takes the a byte input (to be plugged just after the _CRC_verif_)
- Has an option for the file to save to (as the _filesink_ does)
- Using the tag that is attached to the byte stream (you can attach a tag debug to see this tag exact content but in short it contains the CRC result and the frame length), this new block reads the bytes and write them to the file set in the parameters with each line containing the information of a frame: timestamp, hex0, hex1, ... 
Let me know what you think, and if you don't want to make any change to the pull request I'll merge the hex output part.

**Comment by alphapats** [comment]
Thanks @tapparelj 
Good suggestions, will try to implement those and then you can merge if comfortable

**Comment by alphapats** [comment]
Screenshot from 2024-02-14 23-40-05

**Comment by tapparelj** [comment]
Thanks for the changes, it is more versatile now!
I've made minor tweaks to remove the "hex" indication as the block you made works fine with any message, leaving people the choice if they want to connect to the hex output or the string (e.g. connecting both would give this:)
```
15022024_101714,Hello World: 0
15022024_101714,48 65 6c 6c 6f 20 57 6f 72 6c 64 3a 20 30
15022024_101716,Hello World: 1
15022024_101716,48 65 6c 6c 6f 20 57 6f 72 6c 64 3a 20 31
```
Thanks again!

**Pull request merged**
